[package]
name = "kobold"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tmux_interface = "0.2.1"
toml = "0.5.9"
serde_derive = "1.0.143"
serde = "1.0.143"
termion = "1.5.6"